# this action should set up all the dependencies for VILSA including redis database

name: Set up VILSA environment

on:
  workflow_dispatch:    # run this action manually

jobs:
  set_up:
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Azure tools
      run: |
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4
        sudo npm install -g azurite
        # azurite -l local_storage/

    - name: Start redis DB
      run: |
        docker run --name vilsa-db -p 6379:6379 redis
