# this action should set up all the dependencies for VILSA including redis database

name: Set up VILSA environment

on:
#  push:
  workflow_dispatch:    # run this action manually

jobs:
  set_up:
    runs-on: ubuntu-20.04
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    steps:
#    - uses: actions/checkout@v3 commented out cause there is no code to test yet
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Azure tools
      run: |
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4

#    - name: Test with pytest
#          run: |
#            pytest tests/integration_tests